/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orcamento.gui;

import java.net.URL;
import javax.swing.ImageIcon;
import orcamento.code.Calculo;
import orcamento.code.SystemClipboard;
import orcamento.code.Formatter;

/**
 *
 * @author ESCRITURA3
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Tela() {
        initComponents();
        setLocationRelativeTo(null);
        
        URL iconURL = getClass().getResource("/img/logoCaneta.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpOrcamento = new javax.swing.JPanel();
        jlValorAvaliacao = new javax.swing.JLabel();
        jlItbi = new javax.swing.JLabel();
        jlEscritura = new javax.swing.JLabel();
        jlRegistro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfValorAvaliacao = new javax.swing.JTextField();
        jtfItbi = new javax.swing.JTextField();
        jtfEscritura = new javax.swing.JTextField();
        jtfRegistro = new javax.swing.JTextField();
        jtfTotal = new javax.swing.JTextField();
        jbCalcular = new javax.swing.JButton();
        jbCopiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orçamento");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jpOrcamento.setBackground(new java.awt.Color(255, 255, 255));
        jpOrcamento.setName(""); // NOI18N
        jpOrcamento.setPreferredSize(new java.awt.Dimension(300, 300));

        jlValorAvaliacao.setText("Valor da Avaliação:");

        jlItbi.setText("ITBI (2%):");

        jlEscritura.setText("Escritura:");

        jlRegistro.setText("Registro:");

        jLabel1.setText("Total:");

        jtfValorAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfValorAvaliacaoActionPerformed(evt);
            }
        });
        jtfValorAvaliacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfValorAvaliacaoKeyPressed(evt);
            }
        });

        jtfItbi.setEditable(false);
        jtfItbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfItbiActionPerformed(evt);
            }
        });

        jtfEscritura.setEditable(false);
        jtfEscritura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEscrituraActionPerformed(evt);
            }
        });

        jtfRegistro.setEditable(false);
        jtfRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRegistroActionPerformed(evt);
            }
        });

        jbCalcular.setText("Calcular");
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });

        jbCopiar.setText("Copiar");
        jbCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCopiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpOrcamentoLayout = new javax.swing.GroupLayout(jpOrcamento);
        jpOrcamento.setLayout(jpOrcamentoLayout);
        jpOrcamentoLayout.setHorizontalGroup(
            jpOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOrcamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlValorAvaliacao)
                    .addGroup(jpOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlEscritura)
                        .addComponent(jlItbi)
                        .addGroup(jpOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jlRegistro))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfValorAvaliacao, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jtfItbi)
                    .addComponent(jtfRegistro)
                    .addComponent(jtfEscritura)
                    .addComponent(jtfTotal)
                    .addGroup(jpOrcamentoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jpOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCalcular))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jpOrcamentoLayout.setVerticalGroup(
            jpOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOrcamentoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValorAvaliacao)
                    .addComponent(jtfValorAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlItbi)
                    .addComponent(jtfItbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEscritura)
                    .addComponent(jtfEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRegistro)
                    .addComponent(jtfRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jpOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jbCalcular)
                .addGap(5, 5, 5)
                .addComponent(jbCopiar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfValorAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfValorAvaliacaoActionPerformed


    }//GEN-LAST:event_jtfValorAvaliacaoActionPerformed

    private void jtfItbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfItbiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfItbiActionPerformed

    private void jtfRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRegistroActionPerformed

    private void jtfValorAvaliacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorAvaliacaoKeyPressed

        
        
    }//GEN-LAST:event_jtfValorAvaliacaoKeyPressed

    private void jtfEscrituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEscrituraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEscrituraActionPerformed

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        double itbi = 0;
        double escritura = 0;
        double registro = 0;
        double valorAvaliacao = Double.parseDouble(jtfValorAvaliacao.getText()); 
        Calculo calc = new Calculo();
        Formatter form = new Formatter();
        
        jtfValorAvaliacao.setText(form.format(valorAvaliacao));
        
        //ITBI
        itbi = calc.calculoITBI(valorAvaliacao);
        jtfItbi.setText(form.format(itbi));
        
        //Escritura
        escritura = calc.calculoEscritura(valorAvaliacao);
        jtfEscritura.setText(form.format(escritura));
        
        //Registro
        registro = calc.calculoRegistro(valorAvaliacao);
        jtfRegistro.setText(form.format(registro));
                
        
        //Total
        double total = itbi + escritura + registro;
        jtfTotal.setText(form.format(total));
           
        
        
    }//GEN-LAST:event_jbCalcularActionPerformed

    private void jbCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCopiarActionPerformed
        // TODO add your handling code here:
        String stringCopiada = new String();
        
        stringCopiada = "Avaliação: "+ jtfValorAvaliacao.getText() + "\n" +
                        "ITBI (2%): " + jtfItbi.getText()+ "\n" +
                        "Escritura: " + jtfEscritura.getText()+ "\n" +
                        "Registro: " + jtfRegistro.getText()+ "\n\n" +
                        "Total: " + jtfTotal.getText() + "\n"; 
        
        SystemClipboard.copiar(stringCopiada);
        
    }//GEN-LAST:event_jbCopiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JButton jbCopiar;
    private javax.swing.JLabel jlEscritura;
    private javax.swing.JLabel jlItbi;
    private javax.swing.JLabel jlRegistro;
    private javax.swing.JLabel jlValorAvaliacao;
    private javax.swing.JPanel jpOrcamento;
    private javax.swing.JTextField jtfEscritura;
    private javax.swing.JTextField jtfItbi;
    private javax.swing.JTextField jtfRegistro;
    private javax.swing.JTextField jtfTotal;
    private javax.swing.JTextField jtfValorAvaliacao;
    // End of variables declaration//GEN-END:variables
}
